[workspace]
members = ["proc-macro2", "serde_derive"]
resolver = "2"

[patch.crates-io]
proc-macro2 = { path = "proc-macro2" }

[profile.precompiled]
inherits = "release"
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
